source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target '<%= project_name %>' do

    # Utils
    pod 'R.swift', '~> 3.1'
    pod 'SwiftyBeaver', '~> 1.1.0'
    pod 'SwiftyJSON', '~> 3.1'

    # Networking/Cache
    pod 'Reachability', '~> 3.2'
    pod 'Alamofire', '~> 4.0'

    # UI
    pod 'SwiftHEXColors'
    pod 'SVProgressHUD', '~> 2.0.3'
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
          configuration.build_settings['SWIFT_VERSION'] = "3.0"
        end
    end
end