# Dotfiles management
brew "chezmoi"
brew "age"

# Shell
brew "coreutils"
brew "fd"
brew "ripgrep"
brew "jq"
brew "bat"
brew "eza"
brew "fzf"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "gh"
brew "spaceship"
brew "asdf"
brew "tmux"
